# Load Datasets

In [1]:
import pandas as pd
import numpy as np

bat = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\Cricket Analytics & Player Performance Intelligence Dashboard\Data\Processed\T20_Batting_Cleaned.csv")
bowl = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\Cricket Analytics & Player Performance Intelligence Dashboard\Data\Processed\Bowling_t20_Cleaned.csv")
field = pd.read_csv(r"C:\Users\shiv_\OneDrive\Desktop\Cricket Analytics & Player Performance Intelligence Dashboard\Data\Processed\Fielding_t20_Cleaned.csv")

bat = bat.dropna(subset=['Player'])
bowl = bowl.dropna(subset=['Player'])
field = field.dropna(subset=['Player'])
print("Shape of Batting data:", bat.shape)
print("Shape of Bowling data:", bowl.shape)
print("Shape of Fielding data:", field.shape)

Shape of Batting data: (2006, 24)
Shape of Bowling data: (2006, 21)
Shape of Fielding data: (2006, 17)

In [2]:
bat_players = set(bat['Player'])
bowl_players = set(bowl['Player'])
field_players = set(field['Player'])

print("Unique in batting:", len(bat_players))
print("Unique in bowling:", len(bowl_players))
print("Unique in fielding:", len(field_players))

print("Batting ∩ Bowling:", len(bat_players & bowl_players))
print("Batting ∩ Fielding:", len(bat_players & field_players))
print("Bowling ∩ Fielding:", len(bowl_players & field_players))

Unique in batting: 2006
Unique in bowling: 2006
Unique in fielding: 2006
Batting ∩ Bowling: 2006
Batting ∩ Fielding: 2006
Bowling ∩ Fielding: 2006

In [3]:
print(field['Player'].value_counts().head(20))

Player
JD Schoonheim (NL)         1
MS Dhoni (INDIA)           1
AB de Villiers (SA)        1
D Ramdin (WI)              1
Kamran Akmal (PAK)         1
Mushfiqur Rahim (BDESH)    1
Mohammad Shahzad (AFG)     1
DA Miller (SA/World)       1
Umar Akmal (PAK)           1
Shoaib Malik (ICC/PAK)     1
Q de Kock (SA)             1
MJ Guptill (NZ)            1
GC Wilson (IRE)            1
KC Sangakkara (SL)         1
Sarfaraz Ahmed (PAK)       1
BB McCullum (NZ)           1
LRPL Taylor (NZ)           1
DA Warner (AUS)            1
SK Raina (INDIA)           1
Mohammad Nabi (AFG)        1
Name: count, dtype: int64

In [4]:
print(bat.duplicated().sum())
print(bowl.duplicated().sum())
print(field.duplicated().sum())

0
0
0

In [5]:
print("=== Batting ===")
for col in bat.columns:
    if bat[col].dtype == 'object':
        count = (bat[col] == '-').sum()
        if count > 0:
            print(f"{col}: {count}")

print("=== Bowling ===")
for col in bowl.columns:
    if bowl[col].dtype == 'object':
        count = (bowl[col] == '-').sum()
        if count > 0:
            print(f"{col}: {count}")

print("=== Fielding ===")
for col in field.columns:
    if field[col].dtype == 'object':
        count = (field[col] == '-').sum()
        if count > 0:
            print(f"{col}: {count}")

=== Batting ===
Inns: 152
NO: 152
Runs: 152
HS: 152
Ave: 328
BF: 152
SR: 175
100: 152
50: 152
0: 152
4s: 152
6s: 152
=== Bowling ===
Inns: 651
Overs: 651
Mdns: 651
Runs: 651
Wkts: 651
BBI: 865
Ave: 865
Econ: 651
SR: 865
4: 651
5: 651
=== Fielding ===
Inns: 2
Dis: 2
Ct: 2
St: 2
Ct Wk: 2
Ct Fi: 2
MD: 2
D/I: 2

In [6]:
rows_with_dash = bat[bat['Inns'] == '-']
print(rows_with_dash.shape)
rows_with_dash[['Player', 'Mat', 'Inns', 'Runs', 'Ave']].head(10)

(152, 24)

                   Player  Mat Inns Runs Ave
1854      YA Abdulla (SA)    2    -    -   -
1855     Abdur Rauf (PAK)    1    -    -   -
1856    RA Abolarin (NGA)    1    -    -   -
1857      F Achelam (UGA)    1    -    -   -
1858     GW Aldridge (NZ)    1    -    -   -
1859     TR Ambrose (ENG)    1    -    -   -
1860    A Anemogiannis ()    1    -    -   -
1861    S Aravind (INDIA)    1    -    -   -
1862      JC Archer (ENG)    1    -    -   -
1863  Arsalan Qadir (CAN)    1    -    -   -

In [7]:
rows_with_dash_bowl = bowl[bowl['Inns'] == '-']
print(rows_with_dash_bowl.shape)
rows_with_dash_bowl[['Player', 'Mat', 'Inns', 'Wkts']].head(10)

(651, 21)

                    Player  Mat Inns Wkts
1355    Aamer Ikram (PORT)    4    -    -
1356  Aarif Sheikh (NEPAL)   11    -    -
1357      Z Abbasi (Botsw)    1    -    -
1358    Abbas Saad (Saudi)    2    -    -
1359   Abdul Rashid (Belg)    1    -    -
1360   Abdul Shakoor (UAE)    6    -    -
1361   Abdul Shakoor (ROM)    2    -    -
1362    Abraash Khan (CAN)    7    -    -
1363     Abrar Bilal (Aut)    3    -    -
1364       F Achelam (UGA)    1    -    -

In [8]:
numeric_cols_bat = ['Inns', 'NO', 'Runs', 'BF', '100', '50', '0', '4s', '6s', 'Ave', 'SR']
for col in numeric_cols_bat:
    bat[col] = bat[col].replace('-', np.nan)
    bat[col] = pd.to_numeric(bat[col], errors='coerce')

numeric_cols_bowl = ['Inns', 'Overs', 'Mdns', 'Runs', 'Wkts', 'Ave', 'Econ', 'SR', '4', '5']
for col in numeric_cols_bowl:
    bowl[col] = bowl[col].replace('-', np.nan)
    bowl[col] = pd.to_numeric(bowl[col], errors='coerce')

numeric_cols_field = ['Inns', 'Dis', 'Ct', 'St', 'Ct Wk', 'Ct Fi', 'MD']
for col in numeric_cols_field:
    field[col] = field[col].replace('-', np.nan)
    field[col] = pd.to_numeric(field[col], errors='coerce')

In [9]:
for name, df_ in [('Batting', bat), ('Bowling', bowl), ('Fielding', field)]:
    print(f"=== {name} ===")
    for col in df_.columns:
        if df_[col].dtype == 'object':
            count = (df_[col] == '-').sum()
            if count > 0:
                print(f"{col}: {count}")

=== Batting ===
HS: 152
=== Bowling ===
BBI: 865
=== Fielding ===
D/I: 2

In [10]:
bat.info()
bowl.info()
field.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2006 entries, 0 to 2005
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             2006 non-null   object
 1   Span               2006 non-null   object
 2   Start_Year         2006 non-null   int64
 3   End_Year           2006 non-null   int64
 4   Career_Lenght      2006 non-null   int64
 5   Mat                2006 non-null   int64
 6   Inns               1854 non-null   float64
 7   NO                 1854 non-null   float64
 8   Runs               1854 non-null   float64
 9   HS                 2006 non-null   object
 10  HS_Numeric         2006 non-null   object
 11  HS_NotOut          2006 non-null   int64
 12  Ave                1678 non-null   float64
 13  BF                 1854 non-null   float64
 14  SR                 1831 non-null   float64
 15  100                1854 non-null   float64
 16  50                 1854 non-null   float64
 17  0                  1854 non-null   float64
 18  4s                 1854 non-null   float64
 19  6s                 1854 non-null   float64
 20   Runs_Per_Match    2006 non-null   object
 21  Century_Rate       2006 non-null   object
 22  Fifty_Rate         2006 non-null   object
 23  Consistency_Score  2006 non-null   object
dtypes: float64(11), int64(5), object(8)
memory usage: 376.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2006 entries, 0 to 2005
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Player                2006 non-null   object
 1   Span                  2006 non-null   object
 2   Start_ Year           2006 non-null   int64
 3   End_Year              2006 non-null   int64
 4   Career_Length         2006 non-null   int64
 5   Mat                   2006 non-null   int64
 6   Inns                  1355 non-null   float64
 7   Overs                 1355 non-null   float64
 8   Mdns                  1355 non-null   float64
 9   Runs                  1355 non-null   float64
 10  Wkts                  1355 non-null   float64
 11  BBI                   2006 non-null   object
 12  Ave                   1141 non-null   float64
 13  Econ                  1355 non-null   float64
 14  SR                    1141 non-null   float64
 15  4                     1355 non-null   float64
 16  5                     1355 non-null   float64
 17  Wickets_Per_Match     2006 non-null   object
 18  Economy_Score         2006 non-null   object
 19  Bowling_Impact_Score  2006 non-null   object
 20  Five_Wicket_Rate      2006 non-null   object
dtypes: float64(10), int64(4), object(7)
memory usage: 329.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2006 entries, 0 to 2005
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Player                2006 non-null   object
 1   Span                  2006 non-null   object
 2   Start_Year            2006 non-null   int64
 3   End_Year              2006 non-null   int64
 4   Career_Length         2006 non-null   int64
 5   Mat                   2006 non-null   int64
 6   Inns                  2004 non-null   float64
 7   Dis                   2004 non-null   float64
 8   Ct                    2004 non-null   float64
 9   St                    2004 non-null   float64
 10  Ct Wk                 2004 non-null   float64
 11  Ct Fi                 2004 non-null   float64
 12  MD                    609 non-null    float64
 13  D/I                   2006 non-null   object
 14  Catches_Per_Match     2006 non-null   object
 15  Dismissals_Per_Match  2006 non-null   object
 16  Stumping_Rate         2006 non-null   object
dtypes: float64(7), int64(4), object(6)
memory usage: 266.6+ KB

In [13]:
suspect_cols = ['HS_Numeric', 'Century_Rate', 'Fifty_Rate', 'Consistency_Score']
for col in suspect_cols:
    print(col, bat[col].unique()[:8])
    
suspect_cols_bowl = ['Wickets_Per_Match', 'Economy_Score', 'Bowling_Impact_Score', 'Five_Wicket_Rate']
for col in suspect_cols_bowl:
    print(col, bowl[col].unique()[:8])

suspect_cols_field = ['D/I', 'Catches_Per_Match', 'Dismissals_Per_Match', 'Stumping_Rate']
for col in suspect_cols_field:
    print(col, field[col].unique()[:8])

HS_Numeric ['94' '118' '105' '75' '123' '100' '91' '96']
Century_Rate ['0.00' '3.85' '2.41' '2.82' '1.32' '1.54' '1.25' '3.45']
Fifty_Rate ['32.00' '18.27' '18.07' '6.31' '18.31' '19.74' '12.79' '18.46']
Consistency_Score ['86.82' '74.54' '73.85' '67.97' '75.88' '74.68' '72.22' '72.66']
Wickets_Per_Match ['1.34' '0.99' '1.21' '1.33' '1.42' '1.87' '1.03' '1.14']
Economy_Score ['0.14' '0.15' '0.16' '0.12' '0.13' '0.17' '0.11' '0.18']
Bowling_Impact_Score ['0.98' '0.74' '0.89' '1.03' '1.36' '0.76' '0.83' '0.69']
Five_Wicket_Rate ['0.025' '0.000' '0.013' '0.033' '0.044' '0.015' '0.051' '0.053']
D/I ['0.938' '0.923' '0.887' '1.034' '0.719' '0.83' '0.722' '0.619']
Catches_Per_Match ['0.58' '0.83' '0.61' '0.48' '0.37' '0.40' '0.71' '0.60']
Dismissals_Per_Match ['0.93' '0.92' '0.89' '1.03' '0.70' '0.83' '0.72' '0.62']
Stumping_Rate ['0.35' '0.09' '0.28' '0.55' '0.33' '0.43' '0.01' '0.02']

In [14]:
for name, df_ in [('Batting', bat), ('Bowling', bowl), ('Fielding', field)]:
    print(f"=== {name} ===")
    remaining = [col for col in df_.columns if df_[col].dtype == 'object']
    print("Remaining object columns:", remaining)

=== Batting ===
Remaining object columns: ['Player', 'Span', 'HS', 'HS_Numeric', ' Runs_Per_Match ', 'Century_Rate', 'Fifty_Rate', 'Consistency_Score']
=== Bowling ===
Remaining object columns: ['Player', 'Span', 'BBI', 'Wickets_Per_Match', 'Economy_Score', 'Bowling_Impact_Score', 'Five_Wicket_Rate']
=== Fielding ===
Remaining object columns: ['Player', 'Span', 'D/I', 'Catches_Per_Match', 'Dismissals_Per_Match', 'Stumping_Rate']

In [15]:
print([repr(c) for c in bat.columns])
print([repr(c) for c in bowl.columns])
print([repr(c) for c in field.columns])

["'Player'", "'Span'", "'Start_Year'", "'End_Year'", "'Career_Lenght'", "'Mat'", "'Inns'", "'NO'", "'Runs'", "'HS'", "'HS_Numeric'", "'HS_NotOut'", "'Ave'", "'BF'", "'SR'", "'100'", "'50'", "'0'", "'4s'", "'6s'", "' Runs_Per_Match '", "'Century_Rate'", "'Fifty_Rate'", "'Consistency_Score'"]
["'Player'", "'Span'", "'Start_ Year'", "'End_Year'", "'Career_Length'", "'Mat'", "'Inns'", "'Overs'", "'Mdns'", "'Runs'", "'Wkts'", "'BBI'", "'Ave'", "'Econ'", "'SR'", "'4'", "'5'", "'Wickets_Per_Match'", "'Economy_Score'", "'Bowling_Impact_Score'", "'Five_Wicket_Rate'"]
["'Player'", "'Span'", "'Start_Year'", "'End_Year'", "'Career_Length'", "'Mat'", "'Inns'", "'Dis'", "'Ct'", "'St'", "'Ct Wk'", "'Ct Fi'", "'MD'", "'D/I'", "'Catches_Per_Match'", "'Dismissals_Per_Match'", "'Stumping_Rate'"]

In [16]:
bat.columns = bat.columns.str.strip()
bowl.columns = bowl.columns.str.strip()
field.columns = field.columns.str.strip()

In [17]:
print(bat['HS_Numeric'].dtype)
print(bat['Runs_Per_Match'].dtype)  # should work now, after Step 2's strip

object
object

In [18]:
derived_cols_bat = ['HS_Numeric', 'Runs_Per_Match', 'Century_Rate', 'Fifty_Rate', 'Consistency_Score']
for col in derived_cols_bat:
    bat[col] = bat[col].replace('-', np.nan)
    bat[col] = pd.to_numeric(bat[col], errors='coerce')

derived_cols_bowl = ['Wickets_Per_Match', 'Economy_Score', 'Bowling_Impact_Score', 'Five_Wicket_Rate']
for col in derived_cols_bowl:
    bowl[col] = bowl[col].replace('-', np.nan)
    bowl[col] = pd.to_numeric(bowl[col], errors='coerce')

derived_cols_field = ['D/I', 'Catches_Per_Match', 'Dismissals_Per_Match', 'Stumping_Rate']
for col in derived_cols_field:
    field[col] = field[col].replace('-', np.nan)
    field[col] = pd.to_numeric(field[col], errors='coerce')

In [19]:
for name, df_ in [('Batting', bat), ('Bowling', bowl), ('Fielding', field)]:
    print(f"=== {name} ===")
    remaining = [col for col in df_.columns if df_[col].dtype == 'object']
    print("Remaining object columns:", remaining)

=== Batting ===
Remaining object columns: ['Player', 'Span', 'HS']
=== Bowling ===
Remaining object columns: ['Player', 'Span', 'BBI']
=== Fielding ===
Remaining object columns: ['Player', 'Span']

# Merge

In [20]:
merged_t20 = bat.merge(
    bowl,
    on='Player',
    how='outer',
    suffixes=('_bat', '_bowl')
)
print(merged_t20.shape)

(2006, 44)

In [21]:
merged_t20 = merged_t20.merge(
    field,
    on='Player',
    how='outer',
    suffixes=('', '_field')
)
print(merged_t20.shape)

(2006, 60)

In [22]:
merged_t20['has_batting'] = merged_t20['Mat_bat'].notna()
merged_t20['has_bowling'] = merged_t20['Mat_bowl'].notna()

merged_t20['player_role_hint'] = 'Unknown'
merged_t20.loc[merged_t20['has_batting'] & ~merged_t20['has_bowling'], 'player_role_hint'] = 'Batsman'
merged_t20.loc[~merged_t20['has_batting'] & merged_t20['has_bowling'], 'player_role_hint'] = 'Bowler'
merged_t20.loc[merged_t20['has_batting'] & merged_t20['has_bowling'], 'player_role_hint'] = 'All-rounder'

print(merged_t20['player_role_hint'].value_counts())

player_role_hint
All-rounder    2006
Name: count, dtype: int64

In [23]:
merged_t20.info()
merged_t20.isnull().sum()
merged_t20.sample(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2006 entries, 0 to 2005
Data columns (total 63 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Player                2006 non-null   object
 1   Span_bat              2006 non-null   object
 2   Start_Year            2006 non-null   int64
 3   End_Year_bat          2006 non-null   int64
 4   Career_Lenght         2006 non-null   int64
 5   Mat_bat               2006 non-null   int64
 6   Inns_bat              1854 non-null   float64
 7   NO                    1854 non-null   float64
 8   Runs_bat              1854 non-null   float64
 9   HS                    2006 non-null   object
 10  HS_Numeric            1854 non-null   float64
 11  HS_NotOut             2006 non-null   int64
 12  Ave_bat               1678 non-null   float64
 13  BF                    1854 non-null   float64
 14  SR_bat                1831 non-null   float64
 15  100                   1854 non-null   float64
 16  50                    1854 non-null   float64
 17  0                     1854 non-null   float64
 18  4s                    1854 non-null   float64
 19  6s                    1854 non-null   float64
 20  Runs_Per_Match        1763 non-null   float64
 21  Century_Rate          1854 non-null   float64
 22  Fifty_Rate            1854 non-null   float64
 23  Consistency_Score     1672 non-null   float64
 24  Span_bowl             2006 non-null   object
 25  Start_ Year           2006 non-null   int64
 26  End_Year_bowl         2006 non-null   int64
 27  Career_Length         2006 non-null   int64
 28  Mat_bowl              2006 non-null   int64
 29  Inns_bowl             1355 non-null   float64
 30  Overs                 1355 non-null   float64
 31  Mdns                  1355 non-null   float64
 32  Runs_bowl             1355 non-null   float64
 33  Wkts                  1355 non-null   float64
 34  BBI                   2006 non-null   object
 35  Ave_bowl              1141 non-null   float64
 36  Econ                  1355 non-null   float64
 37  SR_bowl               1141 non-null   float64
 38  4                     1355 non-null   float64
 39  5                     1355 non-null   float64
 40  Wickets_Per_Match     1355 non-null   float64
 41  Economy_Score         1355 non-null   float64
 42  Bowling_Impact_Score  1355 non-null   float64
 43  Five_Wicket_Rate      1355 non-null   float64
 44  Span                  2006 non-null   object
 45  Start_Year_field      2006 non-null   int64
 46  End_Year              2006 non-null   int64
 47  Career_Length_field   2006 non-null   int64
 48  Mat                   2006 non-null   int64
 49  Inns                  2004 non-null   float64
 50  Dis                   2004 non-null   float64
 51  Ct                    2004 non-null   float64
 52  St                    2004 non-null   float64
 53  Ct Wk                 2004 non-null   float64
 54  Ct Fi                 2004 non-null   float64
 55  MD                    609 non-null    float64
 56  D/I                   2004 non-null   float64
 57  Catches_Per_Match     2004 non-null   float64
 58  Dismissals_Per_Match  2004 non-null   float64
 59  Stumping_Rate         2004 non-null   float64
 60  has_batting           2006 non-null   bool
 61  has_bowling           2006 non-null   bool
 62  player_role_hint      2006 non-null   object
dtypes: bool(2), float64(41), int64(13), object(7)
memory usage: 960.0+ KB

,Player,Span_bat,Start_Year,End_Year_bat,Career_Lenght,Mat_bat,Inns_bat,NO,Runs_bat,HS,...,Ct Wk,Ct Fi,MD,D/I,Catches_Per_Match,Dismissals_Per_Match,Stumping_Rate,has_batting,has_bowling,player_role_hint
234,Atif Mehmood (ESP),2019-2019,2019,2019,0,9,2.0,2.0,5.0,5*,...,0.0,0.0,0.0,0.000,0.00,0.00,0.0,True,True,All-rounder
614,GRD Munasinghe (ITA),2019-2019,2019,2019,0,8,4.0,1.0,5.0,4*,...,0.0,4.0,NaN,0.571,0.50,0.50,0.0,True,True,All-rounder
1095,MJ Ross (ITA),2019-2019,2019,2019,0,8,5.0,1.0,56.0,34,...,0.0,3.0,NaN,0.428,0.38,0.38,0.0,True,True,All-rounder
1862,TWM Latham (NZ),2012-2017,2012,2017,5,13,10.0,0.0,163.0,39,...,4.0,2.0,NaN,0.461,0.46,0.46,0.0,True,True,All-rounder
355,CJ Boyce (AUS),2014-2016,2014,2016,2,7,2.0,1.0,4.0,3,...,0.0,0.0,0.0,0.000,0.00,0.00,0.0,True,True,All-rounder
523,F Nkhoma (MWI),2019-2019,2019,2019,0,4,NaN,NaN,NaN,-,...,0.0,0.0,0.0,0.000,0.00,0.00,0.0,True,True,All-rounder
1884,Umar Adam (Mald),2019-2019,2019,2019,0,11,10.0,1.0,185.0,53,...,0.0,2.0,NaN,0.181,0.18,0.18,0.0,True,True,All-rounder
449,DJ Willey (ENG),2015-2019,2015,2019,4,28,19.0,7.0,166.0,29*,...,0.0,12.0,NaN,0.428,0.43,0.43,0.0,True,True,All-rounder
1098,MJG Rippon (NL),2013-2018,2013,2018,5,18,11.0,4.0,216.0,42,...,0.0,4.0,NaN,0.235,0.22,0.22,0.0,True,True,All-rounder
1922,Vikramjit Singh (NL),2019-2019,2019,2019,0,1,1.0,0.0,15.0,15,...,0.0,0.0,0.0,0.000,0.00,0.00,0.0,True,True,All-rounder

In [24]:
merged_t20.to_csv(r"../Data/Processed/T20_Player_Profile.csv", index=False)